-- Histats-like tracking — ringan, total all time tetap ada
create table if not exists pageviews (
  id bigint generated by default as identity primary key,
  path text not null,
  title text not null default '',
  referrer text not null default '',
  country text not null default '',
  visitor_id text not null,
  created_at timestamptz not null default now()
);
create index if not exists idx_pageviews_created on pageviews(created_at desc);
create index if not exists idx_pageviews_path on pageviews(path);
create index if not exists idx_pageviews_visitor on pageviews(visitor_id);

-- Rollup all-time per path/title (tidak pernah dihapus)
create table if not exists page_stats_all_time (
  path text primary key,
  title text not null default '',
  total_views bigint not null default 0,
  last_seen timestamptz not null default now()
);

alter table pageviews enable row level security;
alter table page_stats_all_time enable row level security;

-- Admin (authenticated) boleh baca; service role bypass RLS untuk worker
drop policy if exists "admin read pageviews" on pageviews;
create policy "admin read pageviews" on pageviews for select to authenticated using (true);

drop policy if exists "admin read page_stats_all_time" on page_stats_all_time;
create policy "admin read page_stats_all_time" on page_stats_all_time for select to authenticated using (true);

-- Bersihkan raw >90 hari (cron harian via pg_cron tidak tersedia di free, worker akan panggil delete sesekali)
-- Untuk sekarang biarkan manual; total all time aman di page_stats_all_time
