export const COUNTRIES: Array<[string, string]> = [
  ["Indonesia", "🇮🇩"],
  ["Malaysia", "🇲🇾"],
  ["Singapura", "🇸🇬"],
  ["Thailand", "🇹🇭"],
  ["Vietnam", "🇻🇳"],
  ["Filipina", "🇵🇭"],
  ["Brunei", "🇧🇳"],
  ["Kamboja", "🇰🇭"],
  ["Laos", "🇱🇦"],
  ["Myanmar", "🇲🇲"],
  ["Timor-Leste", "🇹🇱"],
  ["Tiongkok (China)", "🇨🇳"],
  ["Jepang", "🇯🇵"],
  ["Korea Selatan", "🇰🇷"],
  ["Korea Utara", "🇰🇵"],
  ["Mongolia", "🇲🇳"],
  ["Taiwan", "🇹🇼"],
  ["India", "🇮🇳"],
  ["Pakistan", "🇵🇰"],
  ["Bangladesh", "🇧🇩"],
  ["Nepal", "🇳🇵"],
  ["Bhutan", "🇧🇹"],
  ["Sri Lanka", "🇱🇰"],
  ["Maladewa", "🇲🇻"],
  ["Afghanistan", "🇦🇫"],
  ["Kazakhstan", "🇰🇿"],
  ["Uzbekistan", "🇺🇿"],
  ["Turkmenistan", "🇹🇲"],
  ["Kirgizstan", "🇰🇬"],
  ["Tajikistan", "🇹🇯"],
  ["Arab Saudi", "🇸🇦"],
  ["Uni Emirat Arab", "🇦🇪"],
  ["Qatar", "🇶🇦"],
  ["Kuwait", "🇰🇼"],
  ["Bahrain", "🇧🇭"],
  ["Oman", "🇴🇲"],
  ["Yaman", "🇾🇪"],
  ["Irak", "🇮🇶"],
  ["Iran", "🇮🇷"],
  ["Suriah", "🇸🇾"],
  ["Lebanon", "🇱🇧"],
  ["Yordania", "🇯🇴"],
  ["Israel", "🇮🇱"],
  ["Palestina", "🇵🇸"],
  ["Turki", "🇹🇷"],
  ["Siprus", "🇨🇾"],
  ["Armenia", "🇦🇲"],
  ["Azerbaijan", "🇦🇿"],
  ["Georgia", "🇬🇪"],
  ["Rusia", "🇷🇺"],
];
